package com.zaleslaw.berlinprotesttracker.domain

enum class DemonstrationCategory {
    EDUCATION_BUDGET,
    LABOR_SOCIAL_HOUSING,
    HEALTH_CARE,
    CLIMATE_ENVIRONMENT,
    MOBILITY_TRANSPORT,
    LOCAL_CIVIC,
    HUMAN_RIGHTS_REPRESSIONS,
    PEACE_GEOPOLITICS,
    INTERNATIONAL_CONFLICT,
    DEMOCRACY_MEMORY_ANTI_EXTREMISM,
    SYSTEM_CRITIQUE_PANDEMIC,
    FAITH_IDENTITY_CULTURE,
    CULTURE_FESTIVAL,
    OTHER_POLITICAL,
    OTHER
}
